import 'package:flutter/material.dart';

class RecipeModel {
  String? title, writer;
  List<dynamic>? description = [] as List;
  int? cookingTime;
  int? servings;
  List<dynamic>? ingredients = [] as List?;
  String? imgPath;
  RecipeModel({
    @required this.title,
    @required this.writer,
    @required this.description,
    @required this.cookingTime,
    @required this.servings,
    @required this.imgPath,
    @required this.ingredients,
  });
  static List<RecipeModel> demoRecipe = [
    RecipeModel(
      title: 'AUTHENTIC HYDERABADI MUTTON BIRYANI RECIPE',
      writer: "akshay",
      description: ['Heat oil and fry onions till golden brown and set aside.',
      "Take mutton and add ingredients and mix well. Set aside to marinate for 1 hour.",
      "For marinating take 1 Kg mutton and add in raw papaya paste, garam masala powder,ginger garlic paste, kashmiri chilli powder,lemon juice ,turmeric powder, fried onions, yogurt /curd, salt and mix well.",
      "Meanwhile soak basmati for 1 hour.",
        "Bring large pot of water to a boil, add salt and add in rice. Cook for 3 to 4 mins till rice is 50% cooked.",
        "Take a large pot, add mutton and cook for 5 mins.",
        "Now top with half of the rice. Top with half of the fried onions, coriander and mint leaves.",
        "Top with more rice and top with fried onions, coriander and mint leaves.",
        "Top with raisins fried in some ghee.",
        "Add in saffron and food colour which is mixed with milk.",
        "Add extracts over the rice.",
        "Seal the rim with a sticky atta dough. Place a lid.",
        "Top with mortar and pestle and some water.",
        "Cook on a very low heat for 45 mins.",
        "Open the lid, fluff up the rice.",
        "Serve hot."
      ],
      cookingTime: 90,
      servings: 6,
      imgPath: 'assets/images/img1.jpg',
      ingredients: [
        'Basmati Rice - 1 kg',
        'Onion - 8 large sliced thinly',
        'Oil - 2 cup',
        'Coriander Leaves - 1 cup chopped finely',
        'Mint Leaves - 1 cup chopped finely',
        'Ghee -¼ cup',
        'Raisins / Kishmish - ½ cup',
        "Saffron a pinch",
        "Milk - ¼ cup",
        "Yellow Food Colour few drops",
        "Rose Extract few drops",
        "Kewra Extract few drops",
        "Mutton - 1 kg",
        "Raw Papaya Paste - 3 tblsp",
        "Shahi Garam Masala Powder - 5 to 6 tblsp",
        "Red Chilli Powder - 1 tblsp",
        "Turmeric Powder - ½ tsp",
        "Ginger Garlic Paste - 4 tblsp",
        "Coriander Leaves - 1 cup chopped",
        "Yogurt - 1 cup",
        "Fried Onions - 2 cups",
        "Green Chillies - 5 to 6 chopped finely",
        "Lemon Juice - 2 to 3 tblsp",
        "Fried Onion Oil - ½ cup",
        "Salt to taste"
      ],
    ),
    RecipeModel(
      title: 'Hyderabadi Chicken Dum Biryani ',
      writer: "arti",
      description:
      ['Slice the onions and fry in oil & ghee mixture until golden brown color. Reserve one of these onions for cooking on dum.',
      "Reserve this oil that was used for frying the onions for cooking on dum (C).",
      "For making the Hyderabad masala powder, take a mixture jar, add caraway seeds, cinnamon stick, cloves, cardamom and grind it into a fine powder.",
      "Take the mixer jar, add ginger, garlic, pudina leaves, coriander leaves, green chilies, a Tsp. of curd, a pinch of salt and grind it into a smooth paste.",
      "In a large bowl, add the chicken, lemon juice, salt and mix well. Then add masala powder, the grinded paste, red chilli powder, coriander powder, pepper powder, fried onion, curd, mix well.",
      "Add 3-4 Tbsp. reserved oil (A. Step 1) and saffron. Mix and set aside for at least 1 hour.",
      "Wash and soak the Basmati rice for 30 minutes.",
      "In a pot, take around 2.5 L of water to cook the rice. Place it on a high heat.",
      "When the water is near to boil, add caraway seeds, vegetable oil and salt. Stir it well to dissolve the salt. The water must be very salty.",
      "During boiling, add the strained basmati rice and stir it well.",
      "Continue to boil it on high heat. Stir a few times very gently and make sure not to break the rice.",
      "Once the rice is half cooked (should take about 7 minutes on high flame) strain the rice and set aside.",
      "Take the heavy bottom pot, place it on low flame, add half the oil & ghee (reserved) that was used for frying the onions. Then arrange the marinated chicken pieces in one layer, and pour the entire marinade as well.",
      "Sprinkle some chopped coriander, mint leaves and fried onions above. Then spread half of the cooked rice on the arranged chicken in the pot",
      "Sprinkle half of the fried onions, half of the chopped mint leaves and coriander leaves.",
      "Spread out the balanced rice as the second layer on top of the first layer of rice.",
      "Place the boiled eggs on top of it and also some green chilies. Then sprinkle the remaining fried onions, chopped mint leaves and coriander leaves.",
      "Now sprinkle the remaining oil & ghee on the rice in a circular motion. In the same way sprinkle a handful of saffron milk on the rice.",
      "Now close the lid and cook for 30 minutes on low flame.",
      "After 30 minutes, turn off the flame and let the biryani rest for 15 minutes before opening.",
      "Serve it with tomato chutney and raita."],
      cookingTime: 90,
      servings: 6,
      imgPath: 'assets/images/img2.jpg',
      ingredients: [
        '2 lb chicken(1 kg)',
        '2 lb basmati rice(1 kg)',
        '6 onions',
        '7 tablespoons oil',
        '4 tablespoons ghee',
        'salt, to taste',
        '2 lemon',
        "1 teaspoon red chili powder",
        "1 teaspoon coriander powder",
        "2 teaspoons pepper powder",
        "1 ½ tablespoons caraway seed",
        "2 cloves",
        "1 cardamom",
        "1 piece cinnamon stick, 2 in (5 cm)",
        "1 piece ginger, 1 in (2.54 cm)",
        "4 cloves garlic",
        "6 green chiles",
        "12 pudina leaves",
        "coriander leaf",
        "2 pinch saffron",
        "¾ cup curd(75 g)",
        "2 tablespoons caraway seed",
        "2 tablespoons vegetable oil",
        "10 pudina leaves",
        "5 hard-boiled eggs",
        "saffron milk",
        "½ cup rice water(120 mL), hot",
        "3 green chiles"

      ],
    ),
    RecipeModel(
      title: 'Karachi Mutton Biriyani ',
      writer: "umar",
      description:
      ['Wash and soak basmati rice in water for 30 minutes and after that cook it with enough more water, salt and some whole garam masala pieces. Cook until done. Drain it and keep aside.',
      "Take a heavy bottomed deep pan, heat oil, add whole garam masala pieces.",
      "Add onion chopped and saute until nice golden brown.",
      "Add ginger garlic paste and saute for a minute.",
      "Add yogurt, mutton pieces, turmeric powder, chilly powder, coriander powder and salt.",
      "Mix well, cover the lid and cook for about 40 -45 minutes (by stirring often; if need add 1/4 cup of water to cook mutton) until the mutton pieces become tender and cooked nicely.",
      "After that add nutmeg powder, mace powder and cardamom powder and garam masala powder; mix well for few minutes.",
      "Now in another pan, add a tablespoon of oil and spread the cooked mutton masala on top evenly.",
      "Above that add the boiled basmati rice.",
      "Sprinkle 1 tbsp of oil on top, fried  onion, lemon wedges, kewra water (mix kewra water with saffron food color and sprinkle it all over  the rice)..",
      "Cover tightly and put on dum for 20 minutes.",
      "Serve with salad and  raitha..."],
      cookingTime: 95,
      servings: 5,
      imgPath: 'assets/images/img3.jpg',
      ingredients: [
        'Tender Mutton-1 kg',
        'Basmati Rice long- 2 cup',
        'Onion-1 large',
        'Ginger garlic paste-2 tbsp',
        'Curd- 1/4 cup',
        'Turmeric powder- 1/2 tsp',
        'Red chilly powder- 2 tsp',
        "Coriander powder-3 tsp",
        "Garam masala powder- 1 tbsp",
        "Cardamom powde- 1/4 tsp",
        "Nutmeg powder- 1/4 tsp",
        "Mace powder- 1/4 tsp",
        "Kewra water-1 tsp",
        "Whole garm masala pieces",
        "Saffron food color-a pinch",
        "Fried onion-1",
        "Oil- 1/2 cup",
        "Lemon wedges-few"

      ],
    ),
    RecipeModel(
      title: 'KARACHI Chicken BIRYANI',
      writer: "zeba",
      description:
      ['Take a bowl add rice, water, and wash thoroughly.Then soak for 20 minutes and site aside.',
      "In boiling water add cooking oil, salt vinegar and stir well.Now, add soaked rice and cook at least 10 minutes",
      "In a mixer, make ginger, garlic, and green chillies paste",
      "In cooking pot add cooking oil",
      "Add cumin seeds, black cardamom, star anise, cinnamon sticks, black pepper, cloves, tomatoes, chilli paste",
      "Add water and cook on low heat for 4 to 5 minutes with lid",
      "Add red chilli, salt, turmeric, garam masala, chicken stock cubes and stir well",
      "Add potatoes and cook on medium heat for 10 minutes with cover",
      "Add yogurt, lemon juice, dried plums and stir well",
      "Add mint leaves.Add fresh coriander and mix well",
      "Then, add chicken and cook on high heat for 10 to 12 minutes",
      "Now mix food colour.Add tomato and lemon slice",
      "Add green chilli and mint leaves",
      "Separately, take a bowl and add mace powder, cumin seeds, nutmeg powder and mix well",
      "In cooking pot, add half quantity of spice.Add boiled rice.",
      "Then add remaining half of spices.Add cooking oil.",
      "Cover the pot and steam cook on low heat for 15 minute",
      "Your Masala Chicken Biryani is Ready",
      "Serve this biryani with raita and salad"
      ],
      cookingTime: 90,
      servings: 6,
      imgPath: 'assets/images/img4.jpg',
      ingredients: [
        '500g Basmati Rice',
        'Water as required',
        '1 tbsp salt',
        '3 tbsp vinegar (sirka)',
        '2 tbsp cooking oil',
        '6-7 green chillies',
        '1 inch peace ginger',
        "7 to 8 cloves garlic",
        "½ cup cooking oil",
        "½ tsp cumin seeds",
        "1 black cardamom",
        "1 star anise",
        "2 cinnamon sticks",
        "2-3 cloves",
        "½ tbsp black pepper (Whole)",
        "3 green cardamom",
        "2 medium size sliced tomatoes",
        "one and half tbsp salt or to taste",
        "½ tbsp red chilli powder",
        "½ tbsp turmeric powder",
        "1 tbsp garam masala",
        "1 chicken stock cube",
        "250g potatoes",
        "8-10 dried plums",
        "¼ cup yogurt",
        "3 tbsp lemon juice",
        "1-2 tbsp fresh coriander chopped",
        "1-2 tbsp mint leaves",
        "½ kg chicken",
        "½ tsp food colour",
        "1 medium sliced tomato",
        "3-4 lemon slices",
        "4-5 green chillies",
        "3 tbsp chopped mint leaves",
        "¼ tsp mace powder",
        "½ tsp roasted and fried cumin seeds",
        "¼ tsp nutmeg powder",
        "2 tbsp cooking oil"
      ],
    ),

    RecipeModel(
      title: 'Bombay Chicken Biryani Recipe',
      writer: "akansha",
      description:
      ['Wash 1 kg chicken, marinate with 1 cup yogurt, 1 ½ tbsp ginger garlic paste',
        "Add 1 tbsp chili powder, 2 tbsp coriander powder",
        "Add juice of 2 lemon, 1 bunch of mint leaves, 6 green chilies, 1 cup plum and salt to taste for 30 minutes.",
        "Heat 1 cup oil in pan, add 4 chopped onion and fry till golden brown",
        "Remove half of the fried onion and spread on a paper. Now add the marinated meat to pan.",
        "Fry well till water dries.",
        "Boil potatoes in steam, cut each into 4 pieces and fry in oil.",
        "Also cut tomatoes in four pieces each.",
        "Fry tomato pieces and add with fried potatoes to the chicken mixture.",
        "Boil 1 kg basmati rice with mint leaves, 6 green chilies, 6 black pepper",
        "Add 4 cloves, salt to taste and water as required till half done.",
        "Now drain out water and keep aside.",
        "Grease another pan and make a layer of boiled rice.",
        "Top with chicken mixture, again top with remaining boiled rice.",
        "Sprinkle the leftover fried onion.",
        "Dissolve ¼ tsp yellow color in 1 cup hot milk.",
        "Pour on top of boiled rice. Also pour juice of 2 lemons and simmer for 10 minutes. Serve hot."

      ],
      cookingTime: 40,
      servings: 4,
      imgPath: 'assets/images/img5.jpg',
      ingredients: [
        'Meat (mutton or chicken) 1 kg',
        'Basmati rice 1 kg',
        'Potatoes 4 large',
        'Lemon 4',
        'Cloves 4',
        'Onion chopped 4',
        'Green chilies 6',
        "Green cardamom 6",
        "Black cardamom 6",
        "Tomatoes chopped 6",
        "Dried plum 1 cup",
        "Hot milk 1 cup",
        "Oil 1 cup",
        "Yogurt 1 cup",
        "Mint leaves 1 bunch",
        "Black cumin seeds 1 tsp",
        "Chili powder 1 tbsp",
        "Yellow color ¼ tsp",
        "Coriander powder 2 tbsp",
        "Ginger garlic paste 1 ½ tbsp",
        "Salt to taste"
      ],
    ),





    RecipeModel(
      title: 'SINDHI BIRYANI',
      writer: "samia",
      description:
      ['Slice the onion and fry it in oil until it is light brown. Take out 1/4 of it and keep aside.',
        "Add Garlic (Lehsan), Ginger (Adrak), tomatoes, prunes (Aaloobukharay), salt, red chili powder, cloves, cardamoms, Black Pepper, (Kali Mirch), Cumin Seeds (Zeera), cinnamon, black cardamom pods and bay leaves to the remaining fried onions.",
        "Fry this until the tomatoes are tender and the water is dry.",
        "Then add meat, yogurt and water (if desired) and cook on medium heat until the meat is tender and the water has evaporated.",
        "On other side boil the potatoes until they're half cooked.",
        "Now, add green chillies, mint, coriander leaves, and the half boiled potatoes to the meat. Simmer for 2, 3 minutes. Your meat curry is done.",
        "Boil the rice with salt, bay leaves, cinnamon sticks and black cardamom and drain the water off when the rice is half done.",
        "Layer the curry with the rice in a pot in one on one layers. Sprinkle the food color, fried onions, and chopped mint leaves on top of the last layer.",
        "Close the lid tightly making sure no steam passes out of the pot and cook on low heat until the rice is done.",
        "Gently mix it before serving.",
        "Serve with Raita."

      ],
      cookingTime: 90,
      servings: 15,
      imgPath: 'assets/images/img6.jpg',
      ingredients: [
        '1.5 kg mutton',
        '5 cups basmati rice (soaked in water for atleast 1/2 an hour)',
        '1/2 kg potato (cut into large chunks)',
        '1.5 cups oil',
        '3 medium onions (sliced)',
        '2 teaspoons garlic paste (Lehsan)',
        '2 teaspoons ginger (Adrak)',
        "1/2 kg tomatoes (chopped)",
        "10-15 prunes (Aaloobukharay)",
        "2 teaspoons salt",
        "4 teaspoons red chili powder",
        "10 cloves (Laung)",
        "8 green cardamoms (Chhoti Ilaichi)",
        "10 pieces black pepper (Kali Mirch)",
        "2 teaspoons cumin seeds (Zeera)",
        "2 cinnamon sticks (Dalchini)",
        "4 black cardamom pods (Bari Ilaichi)",
        "2 bay leaves (Tez Patta)",
        "250 g yogurt",
        "6 green chilies",
        "2 tablespoons coriander leaves (Dhaniya)",
        "2 tablespoons mint leaves (Podina)",
        "3 teaspoons salt",
        "3 bay leaves",
        "3 cinnamon sticks",
        "2 black cardamom pods",
        "2 pinches orange food coloring",
        "1 tablespoon mint leaf (chopped)"
      ],
    ),





    RecipeModel(
      title: 'Delhi Chicken Biryani',
      writer: "Rida",
      description:
      ['Rinse and soak the rice for about 30 minutes.',
        "Once done, add all the whole spices and give it a good boil until the rice gets 80% cooked.",
        "After this, drain the rice and set it aside.",
        "Heat ghee in a large vessel and add all the whole spices again followed by green chillies and ginger garlic paste. Stir fry for about 5-6 minutes.",
        "Then add dum biryani powder or any biryani powder and stir again for 5 minutes.",
        "Now, add chicken pieces and mix everything well.",
        "Once chicken turns tender, add curd and mix again.",
        "Now pour the cooked rice on top of the chicken gravy and add chilli pickle deep in between the rice.",
        "Cover the pan with an aluminium foil and cook for 6-7 minutes",
        "Pour a generous amount of ghee on top and cover for 10 minutes.",
        "Garnish with fried onions, coriander leaves and mint leaves and enjoy!"


      ],
      cookingTime: 45,
      servings: 3,
      imgPath: 'assets/images/img7.jpg',
      ingredients: [
        "For Rice",
        '500 gram Rice',
        '2 Bay leaves',
        '2-3 Cardamom',
        '1 inch Cinnamon stick',
        '1 Black Cardamom',
        '3-4 Cloves',
        '1 Nutmeg',
        "1 Mace",
        "1 tsp Ghee",
        "to taste Salt",
        "For Biryani Base",
        "700 gram Chicken",
        "1 tsp Garam Masala",
        "1 tbsp Red chilli powder",
        "2 Cinnamon sticks",
        "2-3 tbsp Ginger and Garlic paste",
        "4 Cloves",
        "2 tbsp Dum Biryani Masala",
        "1/2 tsp Nutmeg Powder",
        "2-3 Cardamom",
        "2 medium Fried Onions",
        "250 ml Hung Curd",
        "4 Green Chilies",
        "3 tbsp Chopped Fresh Mint",
        "8-10 Raisins and Cashew",
        "2 tbsp Lemon Juice",
        "2 tbsp Green chili and pickle",
        "3 tbsp Ghee",
        "to taste Salt"
      ],
    ),







    RecipeModel(
      title: 'Dhakaiya kachchi Biryani Mutton/Lamb',
      writer: "sonjoy",
      description:
      ['Steps to prepare the meat:',
        "Sprinkle some salt on the meat and let stand for 15-20 minutes. Wash the meat and drain all water.",
        "Take all the spice from red chili to caraway seed, grind.",
        "Take the pot where biryani will be cooked. Add the meat and yogurt, ground spice mix, garlic and ginger paste and salt. Marinate for anywhere between 30 minutes to overnight(see notes).",
        "Steps to prepare the onion:",
        "Add about 3 tablespoon of butter/ghee on a frying pan on medium heat.",
        "Add very thinly sliced onion and sautee until fragrant and golden brown.",
        "Steps to prepare the potato:",
        "Wash, peel and cut the potato in big chinks. Usually into 3 pieces for a medium Idaho potato.",
        "If using, rub some orange food color to the potato.",
        "Sprinkle some salt.",
        "Fry the potatoes until slightly golden on the same pan used for the onion.",
        "Steps to prepare the rice:",
        "Wash rice and drain all water.",
        "Boil 6 cups of water and Add salt.Add the rice.",
        "Turn off the stove at the first sight of water boiling again (bubble forming on the water) after adding the rice. Rice will be uncooked at this point.",
        "Drain the rice completely saving the drained hot water in another clean pot.",
        "Steps to assemble the biryani layers and cook:",
        "Preheat oven to 350 degrees Fahrenheit.",
        "Soak the saffron to the milk.",
        "Add butter/ghee to 1 cup of hot water that was set aside in the rice preparing step.",
        "Add the prepared potatoes on top of the marinated meat.",
        "Sprinkle some fried onion.",
        "Add the alubokhara(prunes), if using.",
        "Add half the water-butter mixture.",
        "Layer in the prepared rice.",
        "Sprinkle the saffron milk.",
        "Make 4-5 indentations from the rice layer through the potato till the meat.",
        "Add the condensed milk through the indentations.",
        "Sprinkle the remaining water-butter mixture.",
        "Sprinkle the remaining fried onion.",
        "Add the remaining hot water in a way that water doesn’t go above the rice layer. You may not need to use all of the hot water.",
        "Cook in the oven for 1.5 hours.",
        "Add the hard boiled eggs.",
        "Serve with salad, kabab and chutney."


      ],
      cookingTime: 240,
      servings: 8,
      imgPath: 'assets/images/img8.jpg',
      ingredients: [
        "2 lb mutton",
        '1 teaspoon ginger paste',
        '2 teaspoon garlic paste',
        '3-4 dry red chili',
        '2-3 stick of cinnamon, half inches each',
        '4-5 green cardamom',
        '1 teaspoon cumin',
        "½ teaspoon cloves",
        "½ teaspoon mace",
        "⅛ teaspoon nutmeg",
        "6-8 allspice (optional)",
        "½ teaspoon caraway seed (optional)",
        "3 tablespoon yogurt",
        "¾ cup ghee or butter",
        "5 medium potato",
        "pinch of orange food color (optional)",
        "½ cup onion, thinly sliced",
        "4 cups basmati or kalijeera rice (I use a 160ml cup to measure my rice. Adjust accordingly)",
        "6 cups water",
        "½ cup condensed milk",
        "2 tablespoon milk",
        "pinch of saffron",
        "10-12 alubokhara (pitted prunes)",
        "4 eggs, hard boiled",
        "Salt, according to taste"
      ],
    ),





    RecipeModel(
      title: 'KOLKATA CHICKEN BIRYANI',
      writer: "Geeta",
      description:
      ['Preparing Biryani Masala Powde: Dry roast all the biryani masala ingredients in batches over medium flame until you get a nice aroma and transfer to a plate to cool down.Then grind them into a smooth powder.',
        "In a large bowl, beat curd, mix all ingredients except chicken to make a smooth paste. Add chicken to the mixture. Mix well and keep aside for at least 1 hr.",
        "Rinse the basmati rice well in the running water to get rid of all the starch. Then soak in water for 30 minutes.",
        "Mix saffron and warm milk together in a bowl and keep aside.",
        "Boil the potato for 7-8 minutes in water. then drain the water and set them aside.",
        "Heat 1-2 tbsp oil. Once the oil is hot enough add boiled eggs, saute for a minute, and set aside.",
        "Fry the potatoes in the same oil by adding a pinch of turmeric powder until sightly golden.",
        "Deep fry the thinly sliced onions until light brown. Place them on a kitchen towel to drain off excess oil.",
        "Heat oil in a pan add sliced onions. Stir and cook until golden brown. Add the marinated chicken. Cover and cook until the chicken is 50% cooked.",
        "In the meanwhile, boil water by adding all ingredients (written under rice preparation) together except rice. The water should be a bit salty. Once the water starts boiling add soaked and drained basmati rice. Let it cook over a high flame until the rice is 60% done.",
        "Now start assembling. Take a heavy bottom pan and grease oil. Put a layer of bay leaves first. It will prevent the biryani from sticking to the bottom.",
        "Spread a layer of chicken with some liquid and a few drops of kewra water. The rice should be ready now. Strain the rice with a colander and directly add to the pan and spread the rice to make a layer. Top the rice with some barista and sprinkle 1/4 teaspoon biryani masala",
        "Spread another layer of chicken with the remaining liquid followed by a final layer of rice, topped with fried egg and potato. Spread some barista, saffron milk, few drops of kewra water, two tablespoons of melted ghee, and 1/4 teaspoon biryani masala.",
        "For placing the biryani in dum, cover with a tight-fitting lid and seal the sides well with the whole wheat dough so that no steam escapes. Now cook on a high flame for 5 minutes and 20 minutes over a low flame. Once done turn off the flame and let it rest for 10 minutes.",
        "Calcutta-style chicken biryani is ready to serve. Serve hot."
      ],
      cookingTime: 80,
      servings: 5,
      imgPath: 'assets/images/img9.jpg',
      ingredients: [
        "For Biryani Masala:",
        '1 mace/javitri whole',
        '1/2 nutmeg/jaipal whole',
        '1 black cardamom',
        '8 green cardamoms',
        '8 cloves',
        '2 cinnamon stick/cacia approx 3 cm',
        '1/3 tsp shah jeera',
        "1/3 tsp shah marich/white paper",
        "1/3 tsp kabab chini",
        "1/2 tsp dried rose petals",
        "For Marinade:",
        "1 kg chicken bone-in large pieces",
        "1 tbsp ginger-garlic paste",
        "1/4 cup curd",
        "1 tsp lemon juice",
        "1/2 tsp coriander powder",
        "1/2 tsp homemade biriyani masala",
        "1/2 tsp red chili powder",
        "salt as needed",
        "For barista:",
        "3 finely sliced onions large size",
        "oil for deep frying I used sunflower oil",
        "For Rice:",
        "500 g basmati rice aged, long-grained",
        "3 l water",
        "salt",
        "1 tsp ghee/clarified butter",
        "4 green cardamoms",
        "4 cloves",
        "2 cinnamon sticks",
        "2 bay leaves",
        "Other Ingredients:",
        "3 large potatoes peeled, washed & cut into halves",
        "4 boiled eggs",
        "1 finely sliced onion large size",
        "2 tbsp ghee",
        "1 tbsp biryani masala powder",
        "1/4 tsp kewra water",
        "1/4 cup warm milk",
        "1 pinch saffron/kesar",
        "whole wheat dough for sealing",
        "4 tbsp oil for cooking I have used sunflower oil"
      ],
    ),







    RecipeModel(
      title: 'Afghani Mutton Biryani Recipe',
      writer: "shehzad khan",
      description:
      ['Cut meat into large pieces and wash thoroughly under cold tap water.',
        "Place meat, cinnamon, cloves, salt, water, garlic and ginger in a large heavy based sauce pan.",
        "Bring to boil and skim off any scum that rises to the top",
        "Reduce heat, cover and allow to boil gently for 40 to 45 minutes until the meat is tender.",
        "Meanwhile, put rice in a sieve and wash it thoroughly under running cold tap until water runs clear.",
        "Soak in plenty of water for 1½ hours.",
        "Drain in a sieve and let it stand for a minute or two.",
        "Fry nuts, raisins and carrots separately in 2 tablespoons of oil in a small frying pan.",
        "keep aside. Heat oil in a large heavy based pan, add onion and while stirring frequently fry for 3-5 minutes.",
        "Add cinnamon stick,cloves, green cardamoms, cumin, meat and 6 cups of stock, add water ifnecessary to make 6 cups.",
        "Bring to boil and add rice to it.",
        "Carefully stir once. Cover and reduce heat to medium and cook for 7-10 minutes.",
        "Gently stir rice.",
        "Do not stir to hard otherwise the rice will break.",
        "Put a layer of carrot, raisins and pine nuts on the top of rice.",
        "Cover with a tight fitting lid, reduce heat to very low and allow to cook for another 7 - 10 minutes until rice is tender.",
        "Fluff up rice with a fork, then transfer it into to a heated serving dish.",
        "Serve with Raita."

      ],
      cookingTime: 75,
      servings: 6,
      imgPath: 'assets/images/img10.jpg',
      ingredients: [
        "1 kilogram lamb meat on the bone",
        "11 cloves",
        "1 large cinnamon sticks",
        "2 teaspoon salt",
        "Gnger Paste 1 tablespoon",
        "1 tablespoon garlic paste",
        "8 cups water",
        " 3 cups basmati rice good quality",
        "3/4 cup cooking oil",
        " 1 large onion skinned & thinly sliced",
        "8 green cardamoms",
        "1 teaspoon cumin seeds zeera",
        "4 carrots, peeled and grated",
        "½ cup green raisins",
        "½ cup pine nuts."
      ],
    ),








  ];
}
